[package]
name = "browserhtml"
version = "0.1.14"
authors = ["The Browserhtml Project Developers"]
license = "MPL-2.0"
repository = "https://github.com/browserhtml/browserhtml.git"
homepage = "https://github.com/browserhtml/browserhtml"
build = "build.rs"
